### ISSUE TITLE
Example 5 fails when using GMT 5.4.5

### ISSUE THREAD

**Issue by molinav** [emolch/gmtpy#7]
This is the traceback:

```sh
vic@onyx:/mnt/vic/Documents/Coding/GitHub/python-gmtpy$ python examples/example5.py
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter TIME_LANGUAGE is deprecated. Use GMT_LANGUAGE instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
gmt: Warning: Parameter PAGE_COLOR is deprecated. Use PS_PAGE_COLOR instead.
Please see http://gmt.soest.hawaii.edu/doc/5.4.5/GMT_Docs.html#new-features-in-gmt-5 for more information.
Traceback (most recent call last):
  File "examples/example5.py", line 95, in <module>
    gmtpy.nice_palette( gmt, palette_widget, guru, cptfile )
  File "/mnt/vic/Documents/Coding/GitHub/python-gmtpy/gmtpy.py", line 4204, in nice_palette
    label_font = gmt.label_font()
  File "/mnt/vic/Documents/Coding/GitHub/python-gmtpy/gmtpy.py", line 3248, in label_font
    return font_tab_rev(self.gmt_config['FONT_LABEL'].split(',')[1])
TypeError: 'dict' object is not callable
```

Apart from the deprecation warnings which are caused by not having a specific defaults string for this GMT version, the error of this issue appears because `font_tab_rev` is defined in the library as a `dict` object but later the library tries to access an item of this `dict` using parentheses instead of brackets.

**Comment by molinav** [comment]
I created a pull request replacing the parentheses with brackets in the problematic code line.

This change is not enough to make `example5.py` work again with GMT 5.4.5. The reason is that the following line creates a temporary file **without** `.cpt` extension for the palette file:
```python
cptfile = gmt.tempfilename()
```
Later in the example, we find this line:
```python
gmt.makecpt( I=True, C="hot", Z=True, out_filename=cptfile, *guru.T())
```
and because `cptfile` does not end with `.cpt`, the file extension is added internally to `out_filename` and we get an `OSError` because the path does not exist.
